web:
  image: docker.io/nginx:stable-alpine
  ports:
    - "8080:80"
  volumes:
    - ./www:/var/www
    - ./config/default.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  image: zendyani/php:7.0.7-fpm-alpine-extended
  volumes:
    - ./www:/var/www
    # - ./config/php-fpm.conf:/usr/local/etc/php-fpm.conf
  links:
    - db:mysql
  ports:
    - 9000  
  command: php-fpm -F
db:
  image: mysql
  volumes:
   - ./mysql:/var/lib/mysql
  environment:
   - DB_NAME=dbName
   - DB_USER=myUser
   - DB_PASS=myPass
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: myUser
    MYSQL_ROOT_PASSWORD: myPass